In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv("Project/trainIdx2_matrix.txt",header=None)

In [34]:
#read testTrack 
#this might cause error 
test = pd.read_csv("Project/testTrack_hierarchy.txt",header=None)
test.columns = test.columns.astype("str")

#split data and convert headers to type str 
test=test['0'].str.split('|',expand=True)

great = pd.DataFrame(data=test)

#rename columns
test.columns=["genreID"+str(i) for i in range(0, len(test.columns))]

test = test.rename(columns={'genreID0': 'userID','genreID1':'trackID','genreID2':'albumID','genreID3':'artistID'})
test['score'] = np.zeros(len(test))


#subset of test 
newtest = test
print(len(newtest))
display(newtest.head(12))

120000

,userID,trackID,albumID,artistID,genreID4,genreID5,genreID6,genreID7,genreID8,genreID9,...,genreID16,genreID17,genreID18,genreID19,genreID20,genreID21,genreID22,genreID23,genreID24,score
0,199810,208019,209288,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
1,199810,74139,277282,271146,113360,173467,173655,192976,146792,48505,...,None,None,None,None,None,None,None,None,None,0.0
2,199810,9903,None,None,33722,123396,79926,73523,None,None,...,None,None,None,None,None,None,None,None,None,0.0
3,199810,242681,190640,244574,61215,17453,274088,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
4,199810,18515,146344,33168,19913,48505,154024,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
5,199810,105760,93458,11616,131552,173467,48505,133159,None,None,...,None,None,None,None,None,None,None,None,None,0.0
6,199812,276940,201356,163237,287681,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
7,199812,142408,112725,275191,158282,173467,242383,207648,48505,133159,...,None,None,None,None,None,None,None,None,None,0.0
8,199812,130023,226816,275191,158282,242383,207648,19913,None,None,...,None,None,None,None,None,None,None,None,None,0.0
9,199812,29189,104694,211701,158282,173467,81520,139095,48505,133159,...,None,None,None,None,None,None,None,None,None,0.0
10,199812,223706,101750,128069,158282,207648,279143,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
11,199812,211361,127464,19438,77904,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0

                         0
0         199808|248969|90
1           199808|2663|90
2          199808|28341|90
3          199808|42563|90
4          199808|59092|90
...                    ...
12403570  249011|270557|90
12403571  249011|273574|90
12403572  249011|286938|90
12403573  249011|287681|80
12403574  249011|295381|90

[12403575 rows x 1 columns]

In [37]:
#this is a subset of train because train is really big 
sub = train #train.iloc[0:1000,:]

#convert and split 
sub.columns = sub.columns.astype("str")
newtrain = sub['0'].str.split('|',expand=True)

#not sure why i need to do this again 
newtrain.columns = newtrain.columns.astype("str")

#rename 
newtrain.rename(columns={'0':'userID','1':'num','2':'score'},inplace=True)

In [38]:
#test big  train small

In [ ]:
 for i in range(len(newtest)): 
    for j in range(len(newtrain)):
        #check if ID's match between test and train
        if newtest.userID[i]==newtrain.userID.iloc[j]:
            #check if train[num] is contained anywhere in the dataset when ID's are matching
            first_flag = newtrain[newtrain.num.isin([newtest.genreID5[i]]or[newtest.genreID6[i]]or[newtest.genreID7[i]]or[newtest.genreID4[i]]or[newtest.trackID[i]]or[newtest.albumD[i]]or[newtest.artistID[i]]or[newtest.genreID8[i]]or[newtest.genreID9[i]]or[newtest.genreID10[i]]or[newtest.genreID11[i]]or[newtest.genreID12[i]]or[newtest.genreID13[i]]or[newtest.genreID14[i]]or[newtest.genreID15[i]]or[newtest.genreID15[i]]or[newtest.genreID16[i]]or[newtest.genreID17[i]]or[newtest.genreID18[i]]or[newtest.genreID19[i]]or[newtest.genreID20[i]]or[newtest.genreID21[i]]or[newtest.genreID22[i]]or[newtest.genreID23[i]]or[newtest.genreID24[i]])].score
            #first_flag is equal to score value 
            #in newtest[score] append the appropriate score 
            newtest['score'][i] = first_flag.values
            
        else: 

            pass 

#display(newtest)
#print(newtest.dtypes)


#next steps: find sum of every row
#then go through each user and find top three and bottom three
#add one or zero to new row. Make sure it matches kaggle output

/var/folders/rj/6xj9852x0fxfntwp49y4v84c0000gn/T/ipykernel_39259/54908286.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newtest['score'][i] = first_flag.values

In [7]:
newomg = newtest

for i in range(len(newomg['score'])): 
    try:
        x = sum(newomg.score[i].astype(int))
        print(x)
        newomg['score'][i] = x
    except:
        pass
    
display(newomg)

0
hi
410
hi
0
hi
40
hi
0
hi
410
hi
0
hi
410
hi
80
hi
410
hi
0
hi
0
hi
0
hi
240
hi
0
hi
160
hi
0
hi
160
hi
330
hi
40
hi
0
hi
0
hi
0
hi
40
hi
160
hi
0
hi
240
hi
160
hi
230
hi
0
hi
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello

,userID,trackID,albumID,artistID,genreID4,genreID5,genreID6,genreID7,genreID8,genreID9,...,genreID16,genreID17,genreID18,genreID19,genreID20,genreID21,genreID22,genreID23,genreID24,score
0,199810,208019,209288,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0
1,199810,74139,277282,271146,113360,173467,173655,192976,146792,48505,...,None,None,None,None,None,None,None,None,None,410
2,199810,9903,None,None,33722,123396,79926,73523,None,None,...,None,None,None,None,None,None,None,None,None,0
3,199810,242681,190640,244574,61215,17453,274088,None,None,None,...,None,None,None,None,None,None,None,None,None,40
4,199810,18515,146344,33168,19913,48505,154024,None,None,None,...,None,None,None,None,None,None,None,None,None,0
5,199810,105760,93458,11616,131552,173467,48505,133159,None,None,...,None,None,None,None,None,None,None,None,None,410
6,199812,276940,201356,163237,287681,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0
7,199812,142408,112725,275191,158282,173467,242383,207648,48505,133159,...,None,None,None,None,None,None,None,None,None,410
8,199812,130023,226816,275191,158282,242383,207648,19913,None,None,...,None,None,None,None,None,None,None,None,None,80
9,199812,29189,104694,211701,158282,173467,81520,139095,48505,133159,...,None,None,None,None,None,None,None,None,None,410
10,199812,223706,101750,128069,158282,207648,279143,None,None,None,...,None,None,None,None,None,None,None,None,None,0
11,199812,211361,127464,19438,77904,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0
12,199813,188441,195380,22935,33722,224280,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0
13,199813,20968,None,None,61215,34486,274088,228419,218185,146103,...,None,None,None,None,None,None,None,None,None,240
14,199813,21571,217069,89183,71345,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0
15,199813,79640,43214,232859,61215,199606,18161,148278,88853,None,...,None,None,None,None,None,None,None,None,None,160
16,199813,184173,292343,196404,33722,271945,224280,None,None,None,...,None,None,None,None,None,None,None,None,None,0
17,199813,111874,117381,231280,131552,199606,144378,None,None,None,...,None,None,None,None,None,None,None,None,None,160
18,199814,122375,99568,105364,214765,131552,176858,91653,67186,None,...,None,None,None,None,None,None,None,None,None,330
19,199814,189043,9481,247092,61215,17453,256783,31104,88853,None,...,None,None,None,None,None,None,None,None,None,40
20,199814,122429,190510,9282,244713,75409,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0
21,199814,52519,116133,37604,48717,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0
22,199814,232332,278284,281022,47898,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0
23,199814,262193,9481,247092,61215,17453,256783,31104,88853,None,...,None,None,None,None,None,None,None,None,None,40
24,199815,64345,80936,288449,61215,199606,48717,51420,181006,233978,...,None,None,None,None,None,None,None,None,None,160
25,199815,118841,170227,247286,147886,181006,67331,None,None,None,...,None,None,None,None,None,None,None,None,None,0
26,199815,275682,294316,252460,176858,34486,199606,None,None,None,...,None,None,None,None,None,None,None,None,None,240
27,199815,30062,23813,180964,34486,199606,268304,18161,228419,99463,...,None,None,None,None,None,None,None,None,None,160
28,199815,258473,47015,258392,131552,176858,228419,None,None,None,...,None,None,None,None,None,None,None,None,None,230
29,199815,129866,56860,82317,158282,139095,242383,279143,None,None,...,None,None,None,None,None,None,None,None,None,0
30,199816,274758,152991,275456,293670,88853,51420,233978,67331,None,...,None,None,None,None,None,None,None,None,None,0.0
31,199816,102153,291534,75966,34486,274088,199606,181653,40467,None,...,None,None,None,None,None,None,None,None,None,0.0
32,199816,183464,2506,273176,173467,19913,146792,48505,196528,None,...,None,None,None,None,None,None,None,None,None,0.0
33,199816,23616,295661,170825,33722,198263,61215,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
34,199816,81699,291534,75966,34486,274088,199606,181653,40467,None,...,None,None,None,None,None,None,None,None,None,0.0
35,199816,46627,18295,90608,17453,35389,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
36,199817,83722,108537,242177,61215,274088,88853,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
37,199817,200166,46917,242177,61215,274088,199606,88853,233978,67331,...,None,None,None,None,None,None,None,None,None,0.0
38,199817,148603,161336,2488,82378,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
39,199817,88745,277800,142632,61215,17453,35389,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
40,199817,144775,46917,242177,61215,274088,88853,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
41,199817,222966,172388,163052,219193,82064,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
42,199818,141875,63416,270715,131552,176858,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
43,199818,290905,173962,None,211809,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
44,199818,59789,274723,3091,61215,199606,266781,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
45,199818,283698,223370,134540,61215,212410,233978,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
46,199818,106788,73659,90443,131552,61215,176858,199606,None,None,...,None,None,None,None,None,None,None,None,None,0.0
47,199818,235999,70121,89183,71345,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
48,199819,202308,152892,108526,33204,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,0.0
49,199819,36793,278270,199204,61215,274088,199606,18161,88853,None,...,None,None,None,None,None,None,None,None,None,0.0

In [30]:
a = 0
newest = newtest

newdf = pd.DataFrame([])

for i in range(len(newest)):
    x = newest.iloc[a:a+6,:]
    x = x.sort_values(by=['score'])
    x['rating'] = [0,0,0,1,1,1]

    

    a = a+6
     #print(a)
     #print(i)
     #display(x)
    newdf = pd.concat([newdf,x])

display(newdf[0:10])

ValueError: Length of values (6) does not match length of index (2)

In [29]:
cols = ['userID', 'trackID']
newdf['TrackID'] = newdf[cols].apply(lambda row: '_'.join(row.values.astype(str)), axis=1)

newdf.head(5)

newest = pd.DataFrame(newdf['TrackID'])
newest = pd.concat([newest,newdf['rating']],axis=1)
newest.columns = newest.columns.astype('str')
newest.rename(columns={"rating":"Predictor"},inplace=True)

newest.to_csv('outputFile',index=False)

newest.head(12)

          TrackID  Predictor
0   199810_208019          0
2     199810_9903          0
4    199810_18515          0
3   199810_242681          1
1    199810_74139          1
5   199810_105760          1
6   199812_276940          0
10  199812_223706          0
11  199812_211361          0
8   199812_130023          1
7   199812_142408          1
9    199812_29189          1